model_name: null
enable_gradient_checkpointing: true
ddp_size: 1
tp_size: 1
cp_size: 1
max_length_per_device: null
optimizer:
  lr: 5e-6
  weight_decay: 1e-2
max_grad_norm: 1.0
scheduler:
  name: constant
  warmup_ratio: 0.1
offload_optimizer: true